### ISSUE TITLE
Fails to build RPM on Fedora 32

### ISSUE THREAD

**Issue by grgcmz** [micahflee/qube-apps#1]
The build process fails with the following error message:
```
...
rpm: /usr/bin/rpmspec; no such file or directory
error: Failed to execute: "rpm -q -qf ...."
...
```

Managed to solve the issue by installing rpm-build rpm-devel and rpmlint with the following command:
```
sudo dnf install rpm-build rpm-devel rpmlint
```
 Not sure if all of these are actually needed tbh, but it worked afterwards. 

Anyway, thanks for the nice tool! :)

**Comment by shaaati** [comment]
Had the same issue on Fedora 33. It seems to be enough to install the `rpm-build` package.

**Comment by tlaurion** [comment]
Only rpm-build is needed @micahflee
